name: Build

on:
  push:
    branches:
      - main
  pull_request:
      branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
      - name: Install dependencies
        run: npm ci

      - name: Build lib
        run: |
          npm run build:lib

      - name: Deploy
        run: |
          sed -i '/dist/d' .gitignore
          git switch -c build
          git add -A
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "Deploy (lib): $GITHUB_SHA"

          git push origin build -f

      - name: Build All
        run: npm run build

      - name: Deploy
        run: |
          git add -A
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git commit -m "Deploy (all): $GITHUB_SHA"
      - uses: actions/upload-artifact@v4
        with:
        name: my-artifact
        path: '**/*.*'

          git push origin build -f

